const types = {
    MOVIE_LOADED: 'MOVIE_LOADED',
    MOVIE_LOADING: 'MOVIE_LOADING',
    ACTORS_LOADED: 'ACTORS_LOADED',
    ACTORS_LOADING: 'ACTORS_LOADING',
    DELETE_MOVIE: 'DELETE_MOVIE',
    CHANGE_MOVIES: 'CHANGE_MOVIES',
    CHANGING_MOVIES: 'CHANGING_MOVIES',
    CHANGE_RATING: 'CHANGE_RATING'
}

export default types;
