const types = {
    FILTER_BY_NAME: 'FILTER_BY_NAME',
    EDIT_MOVIE: 'EDIT_MOVIE',
    DELETE_MOVIE: 'DELETE_MOVIE',
    LIKE_MOVIE: 'LIKE_MOVIE',
    DISLIKE_MOVIE: 'DISLIKE_MOVIE',
    CHANGE_RATING: 'CHANGE_RATING',
    SORT_BY_LIKES: 'SORT_BY_LIKES',
    SORT_BY_RATING: 'SORT_BY_RATING',
    RESET: 'RESET',
    CHANGE_STATUS: 'CHANGE_STATUS'
}

export default types;

