const types = {
    FILTER_BY_NAME: 'FILTER_BY_NAME',
    EDIT_MOVIE: 'EDIT_MOVIE',
    DELETE_MOVIE: 'DELETE_MOVIE',
    LIKE_LOADING: 'LIKE_LOADING',
    LIKE_LOADED: 'LIKE_LOADED',
    RATING_LOADING: 'RATING_LOADING',
    RATING_LOADED: 'RATING_LOADED',
    SORT_BY_LIKES: 'SORT_BY_LIKES',
    SORT_BY_RATING: 'SORT_BY_RATING',
    RESET: 'RESET',
    CHANGE_STATUS: 'CHANGE_STATUS',
    MOVIES_LOADED: 'MOVIES_LOADED',
    MOVIES_LOADING: 'MOVIES_LOADING',
}

export default types;

