const types = {
    FILTER_BY_NAME: 'FILTER_BY_NAME',
    OPEN_MOVIE: 'OPEN_MOVIE',
    LIKE_MOVIE: 'LIKE_MOVIE',
    DISLIKE_MOVIE: 'DISLIKE_MOVIE',
    CHANGE_RATING: 'CHANGE_RATING',
    SORT_BY_LIKES: 'SORT_BY_LIKES',
    SORT_BY_RATING: 'SORT_BY_RATING',
    RESET: 'RESET'
}

export default types;

